#!/bin/bash
# NICUP14's bash interactive cofiguration file

# Configures the prompt
export PS1="\[\e[1;32m\]\W\[\e[0m\] "
# export PS1="\[$(tput setaf 10)\]\W\[$(tput sgr0)\] "

# Sources the user-defined aliases
export BASH_ALIASES_FILE="$HOME/.bash_aliases"
[ -f "$BASH_ALIASES_FILE" ] && source "$BASH_ALIASES_FILE"

# Sources the user-defined functions
export BASH_FUNCTIONS_FILE="$HOME/.bash_functions"
[ -f "$BASH_FUNCTIONS_FILE" ] && source "$BASH_FUNCTIONS_FILE"

# Sets the preffered readline options
set -o vi
shopt -s cdspell
shopt -s cdable_vars
shopt -s checkwinsize
shopt -s cmdhist
shopt -s extglob
shopt -s globstar
shopt -s histappend
command bind '\C-l:clear-screen'

# Sets the preffered blesh options
#[ ! -f ~/.local/share/blesh/ble.sh ] && exit
#source ~/.local/share/blesh/ble.sh
#ble-bind -f 'C-l' 'clear-screen'
#ble-bind -f 'C-c' 'kill-backward-line'
