#!/bin/bash
# NICUP14's custom bash alias definitions

# Bash configuration-related aliases
alias sb='. ~/.bashrc'
alias vb='vim ~/.bashrc'
alias sa='. ~/.bash_aliases'
alias va='vim ~/.bash_aliases'
alias sf='. ~/.bash_functions'
alias vf='vim ~/.bash_functions'

# GNU coreutils-related aliases
alias rm='rm -vi'
alias mv='mv -vi -S .bak'
alias cv='mv -vi -S .bak'
alias ls='ls --color=auto --group-directories-first'
alias la='ls -A'
alias ll='ls -lh'
alias fn='/bin/find -name'

# Radare2-related aliases
alias r2='radare2'

# Programming-related aliases
alias a='./a.out'
alias m='./main'
alias b='bin/main'
alias l='cat bin/Make\ Log.txt'
alias mb='make && bin/main'
alias vm='vim src/main.c*'
alias vmk='vim [Mm]akefile'